import matplotlib.pyplot as opt, matplotlib.animation as animation, pathlib
from Main import dl, intrs, animate

data = open(str(pathlib.Path(__file__).parent.absolute())+"\Data.txt","w")
otr_s, rp = ((-5, 5), (3, 3)), (0, -7)
line = dl(otr_s[0][0], otr_s[0][1], otr_s[1][0]-8, otr_s[1][1]-8)
otr_1 = ((rp[0], otr_s[0][0]), (rp[1], otr_s[1][0]))
otr_2 = ((rp[0], otr_s[0][1]), (rp[1], otr_s[1][1]))
point_1, point_2 = intrs(otr_1, line), intrs(otr_2, line)
otr_3 = ((point_1[0], otr_s[0][1]), (point_1[1], otr_s[1][1]))
otr_4 = ((point_2[0], otr_s[0][0]), (point_2[1], otr_s[1][0]))
point_3 = intrs(otr_3, otr_4)
line_2 = dl(rp[0], point_3[0], rp[1], point_3[1])
point_r = intrs(otr_s, line_2)
data.write("o "+str(otr_s)+'\n')
data.write("l "+str(line)+'\n')
data.write("p "+str(rp)+'\n')
data.write("o "+str(otr_1)+'\n')
data.write("o "+str(otr_2)+'\n')
data.write("p "+str(point_1)+'\n'+"p "+str(point_2)+'\n')
data.write("o "+str(otr_3)+'\n'+"o "+str(otr_4)+'\n')
data.write("p "+str(point_3)+'\n')
data.write("l "+str(line_2)+'\n')
data.write("p "+str(point_r)+'\n')
data.close()
fig = opt.figure()
AnI = animation.FuncAnimation(fig, animate, interval=1000)
opt.xlim(-10, 10)
opt.ylim(-10, 10)
opt.grid()
opt.show()