import matplotlib.pyplot as opt, matplotlib.animation as animation, pathlib, random as rd
from Main import dl, intrs, animate, get_y, cl_int, length, c_int

data = open(str(pathlib.Path(__file__).parent.absolute())+"\Data.txt","w")
otr_s = ((0, 5), (0, 0))
circle_s = (otr_s[0][0], otr_s[1][0], length(otr_s))
circle_1 = (otr_s[0][1], otr_s[1][1], length(otr_s))
point_1 = c_int(circle_s, circle_1)
circle_2 = (point_1[0], point_1[1], length(otr_s))
point_2 = c_int(circle_s, circle_2)
circle_3 = (point_2[0], point_2[1], length(otr_s))
point_3 = c_int(circle_s, circle_3)
data.write("o "+str(otr_s)+'\n')
data.write("c "+str(circle_s)+'\n')
data.write("c "+str(circle_1)+'\n')
data.write("p "+str(point_1)+'\n'+"c "+str(circle_2)+'\n')
data.write("p "+str(point_2)+'\n'+"c "+str(circle_3)+'\n')
data.write("p "+str(point_3)+'\n')
data.close()
fig = opt.figure()
AnI = animation.FuncAnimation(fig, animate, interval=1000)
opt.xlim(-10, 10)
opt.ylim(-10, 10)
opt.grid()
opt.show()